BACKGROUND_COLOR = (70, 48, 79)
FONT_COLOR = (180, 0, 0)
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 500
FPS = 60
UPPER_WINDOW_MARGIN = 5

RACKET_PATH = 'img/racket.png'
RACKET_WIDTH = 35
RACKET_HEIGHT = 150
RACKET_SPEED = 5
LEFT_RACKET_START_X = 5
LEFT_RACKET_START_Y = 200
RIGHT_RACKET_START_X = 560
RIGHT_RACKET_START_Y = 200

BALL_PATH = 'img/sheep.png'
BALL_SIZE = 60
BALL_SPEED = 4
BALL_START_X = BALL_START_Y = 200
BALL_MOVE_DIRECTION_X = BALL_MOVE_DIRECTION_Y = 3
