BACKGROUND_COLOR = (200, 255, 255)
FONT_COLOR = (180, 0, 0)
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 500
FPS = 60
UPPER_WINDOW_MARGIN = 5

RACKET_PATH = 'data/racket.png'
RACKET_WIDTH = 50
RACKET_HEIGHT = 150
RACKET_SPEED = 5
LEFT_RACKET_START_X = 30
LEFT_RACKET_START_Y = 200
RIGHT_RACKET_START_X = 520
RIGHT_RACKET_START_Y = 200

BALL_PATH = 'data/tenis_ball.png'
BALL_SIZE = 40
BALL_SPEED = 4
BALL_START_X = BALL_START_Y = 200
BALL_MOVE_DIRECTION_X = BALL_MOVE_DIRECTION_Y = 3
